# Site settings
title: Karianne's Blog
email: kariannechristina@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site
twitter_username: onphenonmenon
github_username:  onphenomenon
highlighter: pygments

# Build settings
markdown: kramdown
#gems
gems:
  - jekyll-sitemap

